package modelos;
// Generated 20-ene-2021 12:12:07 by Hibernate Tools 5.4.12.Final

/**
 * HibernateSequences generated by hbm2java
 */
public class HibernateSequences implements java.io.Serializable {

	private String sequenceName;
	private Long nextVal;

	public HibernateSequences() {
	}

	public HibernateSequences(String sequenceName) {
		this.sequenceName = sequenceName;
	}

	public HibernateSequences(String sequenceName, Long nextVal) {
		this.sequenceName = sequenceName;
		this.nextVal = nextVal;
	}

	public String getSequenceName() {
		return this.sequenceName;
	}

	public void setSequenceName(String sequenceName) {
		this.sequenceName = sequenceName;
	}

	public Long getNextVal() {
		return this.nextVal;
	}

	public void setNextVal(Long nextVal) {
		this.nextVal = nextVal;
	}

}
