package modelos;
// Generated 20-ene-2021 12:12:07 by Hibernate Tools 5.4.12.Final

/**
 * Importes generated by hbm2java
 */
public class Importes implements java.io.Serializable {

	private ImportesId id;

	public Importes() {
	}

	public Importes(ImportesId id) {
		this.id = id;
	}

	public ImportesId getId() {
		return this.id;
	}

	public void setId(ImportesId id) {
		this.id = id;
	}

}
