package modelos;
// Generated 20-ene-2021 12:12:07 by Hibernate Tools 5.4.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Modulo generated by hbm2java
 */
public class Modulo implements java.io.Serializable {

	private int idModulo;
	private String nombre;
	private Set profesors = new HashSet(0);

	public Modulo() {
	}

	public Modulo(int idModulo) {
		this.idModulo = idModulo;
	}

	public Modulo(int idModulo, String nombre, Set profesors) {
		this.idModulo = idModulo;
		this.nombre = nombre;
		this.profesors = profesors;
	}

	public int getIdModulo() {
		return this.idModulo;
	}

	public void setIdModulo(int idModulo) {
		this.idModulo = idModulo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getProfesors() {
		return this.profesors;
	}

	public void setProfesors(Set profesors) {
		this.profesors = profesors;
	}

}
