package modelos;
// Generated 20-ene-2021 12:12:07 by Hibernate Tools 5.4.12.Final

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private int id;
	private String cantidadPorUnidad;
	private int categoriaId;
	private double iva;
	private int nivelNuevoPedido;
	private String notas;
	private double precioUnidad;
	private String producto;
	private int proveedorId;
	private byte suspendido;
	private int unidadesExistencias;
	private int unidadesPedido;

	public Producto() {
	}

	public Producto(int id, int categoriaId, double iva, int nivelNuevoPedido, double precioUnidad, int proveedorId,
			byte suspendido, int unidadesExistencias, int unidadesPedido) {
		this.id = id;
		this.categoriaId = categoriaId;
		this.iva = iva;
		this.nivelNuevoPedido = nivelNuevoPedido;
		this.precioUnidad = precioUnidad;
		this.proveedorId = proveedorId;
		this.suspendido = suspendido;
		this.unidadesExistencias = unidadesExistencias;
		this.unidadesPedido = unidadesPedido;
	}

	public Producto(int id, String cantidadPorUnidad, int categoriaId, double iva, int nivelNuevoPedido, String notas,
			double precioUnidad, String producto, int proveedorId, byte suspendido, int unidadesExistencias,
			int unidadesPedido) {
		this.id = id;
		this.cantidadPorUnidad = cantidadPorUnidad;
		this.categoriaId = categoriaId;
		this.iva = iva;
		this.nivelNuevoPedido = nivelNuevoPedido;
		this.notas = notas;
		this.precioUnidad = precioUnidad;
		this.producto = producto;
		this.proveedorId = proveedorId;
		this.suspendido = suspendido;
		this.unidadesExistencias = unidadesExistencias;
		this.unidadesPedido = unidadesPedido;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCantidadPorUnidad() {
		return this.cantidadPorUnidad;
	}

	public void setCantidadPorUnidad(String cantidadPorUnidad) {
		this.cantidadPorUnidad = cantidadPorUnidad;
	}

	public int getCategoriaId() {
		return this.categoriaId;
	}

	public void setCategoriaId(int categoriaId) {
		this.categoriaId = categoriaId;
	}

	public double getIva() {
		return this.iva;
	}

	public void setIva(double iva) {
		this.iva = iva;
	}

	public int getNivelNuevoPedido() {
		return this.nivelNuevoPedido;
	}

	public void setNivelNuevoPedido(int nivelNuevoPedido) {
		this.nivelNuevoPedido = nivelNuevoPedido;
	}

	public String getNotas() {
		return this.notas;
	}

	public void setNotas(String notas) {
		this.notas = notas;
	}

	public double getPrecioUnidad() {
		return this.precioUnidad;
	}

	public void setPrecioUnidad(double precioUnidad) {
		this.precioUnidad = precioUnidad;
	}

	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	public int getProveedorId() {
		return this.proveedorId;
	}

	public void setProveedorId(int proveedorId) {
		this.proveedorId = proveedorId;
	}

	public byte getSuspendido() {
		return this.suspendido;
	}

	public void setSuspendido(byte suspendido) {
		this.suspendido = suspendido;
	}

	public int getUnidadesExistencias() {
		return this.unidadesExistencias;
	}

	public void setUnidadesExistencias(int unidadesExistencias) {
		this.unidadesExistencias = unidadesExistencias;
	}

	public int getUnidadesPedido() {
		return this.unidadesPedido;
	}

	public void setUnidadesPedido(int unidadesPedido) {
		this.unidadesPedido = unidadesPedido;
	}

}
