package modelos;
// Generated 20-ene-2021 12:12:07 by Hibernate Tools 5.4.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor implements java.io.Serializable {

	private int id;
	private String ape1;
	private String ape2;
	private String nombre;
	private Set correoelectronicos = new HashSet(0);
	private Set modulos = new HashSet(0);

	public Profesor() {
	}

	public Profesor(int id) {
		this.id = id;
	}

	public Profesor(int id, String ape1, String ape2, String nombre, Set correoelectronicos, Set modulos) {
		this.id = id;
		this.ape1 = ape1;
		this.ape2 = ape2;
		this.nombre = nombre;
		this.correoelectronicos = correoelectronicos;
		this.modulos = modulos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getApe1() {
		return this.ape1;
	}

	public void setApe1(String ape1) {
		this.ape1 = ape1;
	}

	public String getApe2() {
		return this.ape2;
	}

	public void setApe2(String ape2) {
		this.ape2 = ape2;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getCorreoelectronicos() {
		return this.correoelectronicos;
	}

	public void setCorreoelectronicos(Set correoelectronicos) {
		this.correoelectronicos = correoelectronicos;
	}

	public Set getModulos() {
		return this.modulos;
	}

	public void setModulos(Set modulos) {
		this.modulos = modulos;
	}

}
