package modelos;
// Generated 20-ene-2021 12:12:07 by Hibernate Tools 5.4.12.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Tiposbasicos generated by hbm2java
 */
public class Tiposbasicos implements java.io.Serializable {

	private int inte;
	private BigDecimal bigDecimal;
	private BigDecimal bigInteger;
	private byte[] binario;
	private boolean boolean1;
	private byte byte1;
	private char character1;
	private Date dateDate;
	private Date dateTime;
	private Date dateTimestamp;
	private double double1;
	private float float1;
	private long long1;
	private short short1;
	private String stri;
	private String texto;
	private char truefalse1;
	private char yesno1;

	public Tiposbasicos() {
	}

	public Tiposbasicos(int inte, boolean boolean1, byte byte1, char character1, double double1, float float1,
			long long1, short short1, char truefalse1, char yesno1) {
		this.inte = inte;
		this.boolean1 = boolean1;
		this.byte1 = byte1;
		this.character1 = character1;
		this.double1 = double1;
		this.float1 = float1;
		this.long1 = long1;
		this.short1 = short1;
		this.truefalse1 = truefalse1;
		this.yesno1 = yesno1;
	}

	public Tiposbasicos(int inte, BigDecimal bigDecimal, BigDecimal bigInteger, byte[] binario, boolean boolean1,
			byte byte1, char character1, Date dateDate, Date dateTime, Date dateTimestamp, double double1, float float1,
			long long1, short short1, String stri, String texto, char truefalse1, char yesno1) {
		this.inte = inte;
		this.bigDecimal = bigDecimal;
		this.bigInteger = bigInteger;
		this.binario = binario;
		this.boolean1 = boolean1;
		this.byte1 = byte1;
		this.character1 = character1;
		this.dateDate = dateDate;
		this.dateTime = dateTime;
		this.dateTimestamp = dateTimestamp;
		this.double1 = double1;
		this.float1 = float1;
		this.long1 = long1;
		this.short1 = short1;
		this.stri = stri;
		this.texto = texto;
		this.truefalse1 = truefalse1;
		this.yesno1 = yesno1;
	}

	public int getInte() {
		return this.inte;
	}

	public void setInte(int inte) {
		this.inte = inte;
	}

	public BigDecimal getBigDecimal() {
		return this.bigDecimal;
	}

	public void setBigDecimal(BigDecimal bigDecimal) {
		this.bigDecimal = bigDecimal;
	}

	public BigDecimal getBigInteger() {
		return this.bigInteger;
	}

	public void setBigInteger(BigDecimal bigInteger) {
		this.bigInteger = bigInteger;
	}

	public byte[] getBinario() {
		return this.binario;
	}

	public void setBinario(byte[] binario) {
		this.binario = binario;
	}

	public boolean isBoolean1() {
		return this.boolean1;
	}

	public void setBoolean1(boolean boolean1) {
		this.boolean1 = boolean1;
	}

	public byte getByte1() {
		return this.byte1;
	}

	public void setByte1(byte byte1) {
		this.byte1 = byte1;
	}

	public char getCharacter1() {
		return this.character1;
	}

	public void setCharacter1(char character1) {
		this.character1 = character1;
	}

	public Date getDateDate() {
		return this.dateDate;
	}

	public void setDateDate(Date dateDate) {
		this.dateDate = dateDate;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public Date getDateTimestamp() {
		return this.dateTimestamp;
	}

	public void setDateTimestamp(Date dateTimestamp) {
		this.dateTimestamp = dateTimestamp;
	}

	public double getDouble1() {
		return this.double1;
	}

	public void setDouble1(double double1) {
		this.double1 = double1;
	}

	public float getFloat1() {
		return this.float1;
	}

	public void setFloat1(float float1) {
		this.float1 = float1;
	}

	public long getLong1() {
		return this.long1;
	}

	public void setLong1(long long1) {
		this.long1 = long1;
	}

	public short getShort1() {
		return this.short1;
	}

	public void setShort1(short short1) {
		this.short1 = short1;
	}

	public String getStri() {
		return this.stri;
	}

	public void setStri(String stri) {
		this.stri = stri;
	}

	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	public char getTruefalse1() {
		return this.truefalse1;
	}

	public void setTruefalse1(char truefalse1) {
		this.truefalse1 = truefalse1;
	}

	public char getYesno1() {
		return this.yesno1;
	}

	public void setYesno1(char yesno1) {
		this.yesno1 = yesno1;
	}

}
