package modelos;
// Generated 20-ene-2021 12:12:07 by Hibernate Tools 5.4.12.Final

/**
 * TotalesMensuales generated by hbm2java
 */
public class TotalesMensuales implements java.io.Serializable {

	private TotalesMensualesId id;

	public TotalesMensuales() {
	}

	public TotalesMensuales(TotalesMensualesId id) {
		this.id = id;
	}

	public TotalesMensualesId getId() {
		return this.id;
	}

	public void setId(TotalesMensualesId id) {
		this.id = id;
	}

}
