package modelos;
// Generated 20-ene-2021 12:12:07 by Hibernate Tools 5.4.12.Final

/**
 * VEmpleados1 generated by hbm2java
 */
public class VEmpleados1 implements java.io.Serializable {

	private VEmpleados1Id id;

	public VEmpleados1() {
	}

	public VEmpleados1(VEmpleados1Id id) {
		this.id = id;
	}

	public VEmpleados1Id getId() {
		return this.id;
	}

	public void setId(VEmpleados1Id id) {
		this.id = id;
	}

}
