package modelos;
// Generated 20-ene-2021 12:12:07 by Hibernate Tools 5.4.12.Final

/**
 * VNuevaId generated by hbm2java
 */
public class VNuevaId implements java.io.Serializable {

	private int id;
	private String producto;
	private Integer proveedorId;
	private Integer categoriaId;
	private String cantidadPorUnidad;

	public VNuevaId() {
	}

	public VNuevaId(int id, String producto) {
		this.id = id;
		this.producto = producto;
	}

	public VNuevaId(int id, String producto, Integer proveedorId, Integer categoriaId, String cantidadPorUnidad) {
		this.id = id;
		this.producto = producto;
		this.proveedorId = proveedorId;
		this.categoriaId = categoriaId;
		this.cantidadPorUnidad = cantidadPorUnidad;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	public Integer getProveedorId() {
		return this.proveedorId;
	}

	public void setProveedorId(Integer proveedorId) {
		this.proveedorId = proveedorId;
	}

	public Integer getCategoriaId() {
		return this.categoriaId;
	}

	public void setCategoriaId(Integer categoriaId) {
		this.categoriaId = categoriaId;
	}

	public String getCantidadPorUnidad() {
		return this.cantidadPorUnidad;
	}

	public void setCantidadPorUnidad(String cantidadPorUnidad) {
		this.cantidadPorUnidad = cantidadPorUnidad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VNuevaId))
			return false;
		VNuevaId castOther = (VNuevaId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getProducto() == castOther.getProducto()) || (this.getProducto() != null
						&& castOther.getProducto() != null && this.getProducto().equals(castOther.getProducto())))
				&& ((this.getProveedorId() == castOther.getProveedorId())
						|| (this.getProveedorId() != null && castOther.getProveedorId() != null
								&& this.getProveedorId().equals(castOther.getProveedorId())))
				&& ((this.getCategoriaId() == castOther.getCategoriaId())
						|| (this.getCategoriaId() != null && castOther.getCategoriaId() != null
								&& this.getCategoriaId().equals(castOther.getCategoriaId())))
				&& ((this.getCantidadPorUnidad() == castOther.getCantidadPorUnidad())
						|| (this.getCantidadPorUnidad() != null && castOther.getCantidadPorUnidad() != null
								&& this.getCantidadPorUnidad().equals(castOther.getCantidadPorUnidad())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getProducto() == null ? 0 : this.getProducto().hashCode());
		result = 37 * result + (getProveedorId() == null ? 0 : this.getProveedorId().hashCode());
		result = 37 * result + (getCategoriaId() == null ? 0 : this.getCategoriaId().hashCode());
		result = 37 * result + (getCantidadPorUnidad() == null ? 0 : this.getCantidadPorUnidad().hashCode());
		return result;
	}

}
