package modelos;
// Generated 20-ene-2021 12:12:07 by Hibernate Tools 5.4.12.Final

/**
 * VNueva generated by hbm2java
 */
public class VNueva implements java.io.Serializable {

	private VNuevaId id;

	public VNueva() {
	}

	public VNueva(VNuevaId id) {
		this.id = id;
	}

	public VNuevaId getId() {
		return this.id;
	}

	public void setId(VNuevaId id) {
		this.id = id;
	}

}
